### ISSUE TITLE
Use in App router with authOptions obj

### ISSUE THREAD

**Issue by aychernov** [Nekonyx/next-auth-steam#15]
How to use SteamProvider without req?

I`m use something like this structure:

```typescript
import NextAuth from "next-auth"
import {authOptions} from "@/lib/auth";

const handler = NextAuth(authOptions)

export {handler as GET, handler as POST}
``` 

And my authOptions:
```
export const authOptions: NextAuthOptions = {
    pages: {
        signIn: '/sign-in',
    },
    providers: [
        SteamProvider(req? ,{
            clientId: ...!,
            callbackUrl: ...!
        }),
}
```

Where i`m getting error about req and callbackUrl not found and define
Some solutions or advice?
![image](https://github.com/Nekonyx/next-auth-steam/assets/67840786/112a4fcd-2d5d-4091-b271-44f9b3a904a9)

**Comment by jhammond2012** [comment]
I am getting the same
![image](https://github.com/Nekonyx/next-auth-steam/assets/3857428/95e2d7f4-4cfb-49ce-bedc-24062a925a37)

I am guessing that I should downgrade next for now?

**Comment by Nekonyx** [comment]
Nope, you can type `// @ts-expect-error` for now.
It seems Next.js or next-auth made some breaking changes in their API. Gonna take a look ASAP.

**Comment by Nekonyx** [comment]
Fixed
