### ISSUE TITLE
Question about `app-router-get-server-session` example.

### ISSUE THREAD

**Issue by tbntdima** [Nekonyx/next-auth-steam#23]
Hi, I have a question about [app-router-get-server-session](https://github.com/Nekonyx/next-auth-steam/tree/master/examples/app-router-get-server-session) example.

Based on the [next-auth docs](https://next-auth.js.org/configuration/nextjs#getserversession), it is required to pass the options to `getServerSession`. In the example we are not passing anything and still get the session. I'm a bit confused why it works.
In addition, we cannot really pass options since we need to wrap options with `handler(req, ctx)`. Can you please direct me to some sources I can read to understand it or explain it? 🙏

**Comment by tbntdima** [comment]
Ok, I think I started to understand.
So in context of RSC, I should use it like this, right?
```ts
getServerSession(getAuthOptions())
```
I was worried that we need to pass request to forward it to `SteamProvider`.
But `getServerSession` doesn't care about providers, it cares about the `callbacks`.

**Comment by OSHORDESMOND** [comment]
> Hi, I have a question about [app-router-get-server-session](https://github.com/Nekonyx/next-auth-steam/tree/master/examples/app-router-get-server-session) example.
> 
> Based on the [next-auth docs](https://next-auth.js.org/configuration/nextjs#getserversession), it is required to pass the options to `getServerSession`. In the example we are not passing anything and still get the session. I'm a bit confused why it works. In addition, we cannot really pass options since we need to wrap options with `handler(req, ctx)`. Can you please direct me to some sources I can read to understand it or explain it? 🙏

**Comment by OSHORDESMOND** [comment]
getServerSession(getAuthOptions())
