### ISSUE TITLE
button customization

### ISSUE THREAD

**Issue by kkagill** [Nekonyx/next-auth-steam#5]
Thanks a lot for this awesome library! I have two questions.

1. Can this button be customized? 
![image](https://user-images.githubusercontent.com/7738916/236393118-32f123e8-d696-4e8b-af52-0eb34aafb44f.png)

2. Is there a way I can go straight to steam's login page by clicking sign in button below? because clicking on `sign in` directs to another `sign in with steam` button (above) which seems repetitive. 
![image](https://user-images.githubusercontent.com/7738916/236393755-e28a732e-71a9-4fcb-81ea-61b8583729ed.png)

Thanks!

**Comment by Nekonyx** [comment]
Hey, thanks!

1. Yes, this button can be customized. Just pass `style` property:
```ts
export interface OAuthProviderButtonStyles {
  logo: string
  logoDark: string
  bg: string
  bgDark: string
  text: string
  textDark: string
}
```
2. Yep, just do this:
```ts
import { signIn } from 'next-auth/react'

signIn('steam')
```

**Comment by Nekonyx** [comment]
Small note: I would rather import `PROVIDER_ID` from the library than specifying `steam` directly:
```ts
import { PROVIDER_ID } from 'next-auth-steam'
import { signIn } from 'next-auth/react'

signIn(PROVIDER_ID)
```

But it's up to you.

**Comment by kkagill** [comment]
Thanks a lot! so much better :)
