### ISSUE TITLE
Schema changes required

### ISSUE THREAD

**Issue by alexevladgabriel** [Nekonyx/next-auth-steam#6]
I would like to not make a schema modification for a field for steamId and use the already existing `providerAccountId`.
https://github.com/Nekonyx/next-auth-steam/blob/3fee1f0465ad55d112167074e4ca2db23e66829b/src/steam.ts#L85

**Comment by Nekonyx** [comment]
Hi, can you explain exactly what needs to be done and why it needs to be done?

**Comment by alexevladgabriel** [comment]
> Hi, can you explain exactly what needs to be done and why it needs to be done?

When using Steam Provider it requires changing the schema of the database to add steamID column in the accounts , I would want to not do that, and use already existing field providerAccountId.

**Comment by Nekonyx** [comment]
And do you want to replace `steamId` with `providerAccountId`, or remove it completely?
